src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
//use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{
    const HEAT= [
        0 => 'Electric',
        1 => 'Gaz'
    ];
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="boolean", options= {"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_code;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;
    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;
    /**
     * @var File|null
     * @Assert\File(maxSize="5242880", mimeTypes={
     *  "image/png", 
     *  "image/jpeg", 
     *  "image/webp", 
     *  "application/pdf"})
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $updated_at;
    
    public function __construct(){
        $this->createdAt= new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getAdresseCode(): ?string
    {
        return $this->adresse_code;
    }

    public function setAdresseCode(string $adresse_code): self
    {
        $this->adresse_code = $adresse_code;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * 
     * @return self
     */
    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param ?File|null $imageFile
     * 
     * @return self
     */
    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        if ($imageFile) {
            $this->updated_at = new \DateTime('now');
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    /**
     * @param \DateTimeInterface $updated_at
     * 
     * @return self
     */
    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('price')
            ->add('adresse')
            ->add('city')
            ->add('rooms')
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false,
                
            ])
            ->add('bedrooms')
            ->add('sold')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoice()
            ])
            ->add('adresse_code')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }
    public function getChoice()
    {
        $choice = Property::HEAT;
        $output = [];
        foreach($choice as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/Property/PropertyController.php
<?php

namespace App\Controller\Property;

use App\Entity\Contact;
use App\Entity\Property;
use App\Form\ContactType;
use App\Entity\PropertySearch;
use Doctrine\ORM\EntityManager;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
//use Doctrine\ORM\EntityManagerInterface;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;
    /**
     * @var EntityManager
     */
    private $em;
    /**
     * @param PropertyRepository $repository
     * @param EntityManager $em
     * 
     * @return void
     */
    public function __construct(PropertyRepository $repository)
    {
        return $this->repository= $repository;
                //$this->em = $em;
    }
    /**
     * @Route("/biens", name="properties")
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1), /*page number*/
            12 /*limit per page*/
    );
        
        return $this->render('property/index.html.twig', [
            'controller_name' => 'PropertyController',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements= {"slug" : "[a-z0-9\-]*"})
     * @return Response
     * @param Property $property
     * @param string $slug
     * 
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $contactNotification): Response
    {
        if($property->getSlug() !== $slug){
            $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()],
                 301);
        }
        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            /*$contactNotification->notify($contact);*/
            $this->addFlash('success', 'Votre message a été bien envoyé');
            $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()],
            );

        }
        return $this->render('property/show.html.twig', [
            'controller_name' => 'PropertyController',
            'property' =>$property,
            'form' => $form->createView()
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}


{% block title %}Tous nos biens{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
        {{ form_start(form) }}
        <div class="form-row">
            <div class="col">
                {{ form_row(form.minSurface) }}
            </div>
            <div class="col">
                {{ form_row(form.maxPrice) }}
            </div>
            <div class="col">
                {{ form_row(form.options) }}
            </div>
            <button class="btn btn-primary">Rechercher</button>
            </div>
        {{ form_end(form) }}
        </div>
    </div>
    <div class="container">
        <h2> Voici nos biens </h2>
        <div class="row">
            {% for property in properties %}
                {{ include('property.html.twig') }}
            {% endfor %}
        </div>
            <div class="pagination">
                {{ knp_pagination_render(properties) }}
            </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block title %} {{ property.title }} {% endblock %}
{% block body %}
    <div class="jumbotron">
        <div class="container">    
            <div class="row">
                <div class="col-md-8">
                    {% if property.filename %}
                        <img src="/images/properties/{{ property.filename }}" alt="card-img-top" style="width: 60%; height:auto;">
                    {% else %}
                        <img src="{{ '/images/properties/images.jpg' }}" alt="card-img-top" style="width: 60%; height: auto;">
                    {% endif %}
                </div>
                <div class="col-md-4">
                        <h1>{{ property.title }} </h1>
                        <h2> {{ property.rooms }} pièces - {{ property.surface }} m²</h2>
                    <div class="text-primary" style="font-size: 2rem; font-weight: bold"> {{ property.formattedPrice }} Fbu</div>
                        <a class="btn btn-primary" href="#">Contacter nous</a>
                        <div id="contactForm" class="mt-4">
                            {{ form_start(form) }}
                                <div class="row">
                                    <div class="col">{{ form_row(form.firstname) }}</div>
                                    <div class="col">{{ form_row(form.lastname) }}</div>
                                </div>
                                <div class="row">
                                    <div class="col">{{ form_row(form.phone) }}</div>
                                    <div class="col">{{ form_row(form.email) }}</div>
                                </div>
                                {{ form_rest(form) }}
                                <div class="form-group">
                                    <button class="btn btn-primary">Envoyer</button>
                                </div>
                            {{ form_end(form) }}
                        </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <p>
            {{ property.description | nl2br }}
        </p>
        <div class="row">
            <div class="col-md-8">
                <h2>Caracteristiques</h2>
                <div class="col-md-4">
                    <table class="table table-striped">
                        <tr>
                            <td>Surface: </td>
                            <td> {{ property.surface }} m²</td>
                        </tr>
                        <tr>
                            <td>Pièces</td>
                            <td> {{ property.rooms }} </td>
                        </tr>
                        <tr>
                            <td>Chambres</td>
                            <td> {{ property.bedrooms }} </td>
                        </tr>
                        <tr>
                            <td>Chauffages</td>
                            <td> {{ property.heatType }} </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">
                            {{ option.name }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
   
{% endblock body %} 